app_id: "4c14dd92-e39a-4538-8346-4e7c40cee08c"
app_secret: "wRaJcSkG:0IPf12LT7PaKhUzY?=.rhPV"
redirect: "http://localhost:8000/tutorial/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"